<?php

namespace Oscar\Test\Classes;

use Oscar\Classes\CsvReader;
use PHPUnit\Framework\TestCase;

class CsvReaderTest extends TestCase
{
    public function setUp(): void
    {
        $this->reader = new CsvReader();
        parent::setUp(); // TODO: Change the autogenerated stub
    }

    public function testReadFileNull()
    {
        $arr = $this->reader->readFile(null);
        $this->assertEmpty($arr);
    }
}
